"""
PostgreSQL access layer (kept under the original module/function names so the
models don't need rewiring). Despite the legacy filename, this connects to
PostgreSQL via psycopg2 using a threaded connection pool for throughput.

All config comes from environment variables (no credentials in code):
    DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, DB_POOL_MAX
"""
import os

import psycopg2
from psycopg2 import pool
from psycopg2.extras import RealDictCursor

_pool = None


def _get_pool():
    global _pool
    if _pool is None:
        _pool = psycopg2.pool.ThreadedConnectionPool(
            1,
            int(os.environ.get("DB_POOL_MAX", 20)),
            host=os.environ.get("DB_HOST", "localhost"),
            port=int(os.environ.get("DB_PORT", 5432)),
            user=os.environ.get("DB_USER", "voting"),
            password=os.environ.get("DB_PASSWORD", "votingpass"),
            dbname=os.environ.get("DB_NAME", "votingdb"),
            sslmode=os.environ.get("DB_SSLMODE", "prefer"),
        )
    return _pool


class MySQLConnection:
    """Name kept for backwards compatibility; this is a PostgreSQL connection."""

    def __init__(self, db=None):
        self.db = db  # accepted for compatibility; the real DB is set via env

    def query_db(self, query, data=None):
        conn = _get_pool().getconn()
        try:
            with conn.cursor(cursor_factory=RealDictCursor) as cursor:
                cursor.execute(query, data)
                verb = query.strip().lower()
                if verb.startswith("insert"):
                    conn.commit()
                    # Return the id generated by the row's SERIAL/sequence,
                    # mirroring MySQL's cursor.lastrowid behaviour.
                    try:
                        cursor.execute("SELECT lastval() AS id")
                        return cursor.fetchone()["id"]
                    except Exception:
                        return True
                if verb.startswith("select"):
                    rows = cursor.fetchall()
                    conn.commit()
                    return rows
                conn.commit()
                return True
        except Exception as e:
            conn.rollback()
            print("Database error:", e)
            return False
        finally:
            _get_pool().putconn(conn)


def connectToMySQL(db=None):
    """Factory kept under its original name; returns a PostgreSQL connection."""
    return MySQLConnection(db)
